apiVersion: v1
kind: Service
metadata:
  name: scielo-app-svc
  labels:
    app: scielo-app

spec:
  type: NodePort

  ports:
    - name: webapp
      port: 8000
      targetPort: 8000
      protocol: TCP

  selector:
    app: scielo-app
