apiVersion: apps/v1
kind: Deployment
metadata:
  name: scielo-app

spec:
  template:
    spec:
      containers:
      - name: webapp
        envFrom:
        - secretRef:
            name: secrets-scielo-pf

      tolerations:
      - key: app
        operator: Equal
        value: scielo-pf
        effect: NoSchedule

      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: scielo-pf-data-pvc
