apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: qa1-scielo-br

namePrefix: qa1-

replicas:
  - name: scielo-app
    count: 1

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:41d47d14c98e5b8d636a455ac12090985f7b81b916b0d4b1464d502cb8def5e5

# JSON patch sรณ para Service
patches:
  - target:
      kind: Service
      name: scielo-app-svc
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32642

# Strategic merge para Deployment
patchesStrategicMerge:
  - patch-deployment.yaml
