apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa1-scielo-br

resources:
  - ../base

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:c774de53e9e8df44e5ddcc8bc60e586dc6efdab14a2add4a9bd8c75ddc189145
