apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa1-scielo-br

resources:
  - ../base

images:
  - name: infrascielo/opac_5
    newName: infrascielo/opac_5
    digest: sha256:8c03bf1ae0f696f8eb9f1313967e512eb01690c8dbd4b9b218beb0e74442e52b
