apiVersion: apps/v1
kind: Deployment
metadata:
  name: scielo-app

spec:
  template:
    spec:
      containers:
      - name: webapp
        envFrom:
        - secretRef:
            name: secrets-qa1-scielo-br

      tolerations:
      - key: app
        operator: Equal
        value: homologacao
        effect: NoSchedule

      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: qa1-scielo-br-data-pvc
